name: note_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  image_picker: ^1.1.2
  just_audio: ^0.10.5
  path_provider: ^2.1.3
  video_player: ^2.10.0
  shared_preferences: ^2.5.3
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  firebase_auth: ^6.1.0
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^7.1.2
  equatable: ^2.0.7
  http: ^1.2.3
  go_router: ^17.0.0

dependency_overrides:
  record_linux: ^1.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
